THRESHOLD = 0.5
DEBUG_MODE = False
SAME_WAV_DETECTIONS = 8
CONTROL_MODEM_FLAG = False
TO_LOG_PREDICTION = False
SAVE_PKL_FILES = False
MAIL_RESULTS = False
CAMERA_IP = '185.32.179.204:8181'
CAMERA_USERNAME = 'admin'
CAMERA_PASSWORD = 'vnex1199'
BASE_PATH = "/home/pi"
# YOLO_MODEL_PATH = f"{BASE_PATH}/image_process_sys/models/yolov8n_maritime.pt"
YOLO_MODEL_PATH = f"{BASE_PATH}/image_process_sys/models/trawler.pt" # yolov5 model
IMAGE_PATH = f"{BASE_PATH}/image_process_sys/images"
DATA_PATH = f"{BASE_PATH}/ship_noise_sys/data/"
LOGS_PATH = f"{BASE_PATH}/ship_noise_sys/csv_logs"
MOVED_WAVS_PATH = f"{BASE_PATH}/ship_noise_sys/data_post_process"
RAW_ONESEC_DETECTION_PATH = f"{BASE_PATH}/ship_noise_sys/data_raw_oneSec_detection_wavs"
SOUND_MODEL_PATH = f"{BASE_PATH}/ship_noise_sys/models/model_24khz.pkl"
DEMON_PATH = f"{BASE_PATH}/ship_noise_sys/Demon_1s_24khz"